"""empty message

Revision ID: f3e536cc7cac
Revises: 
Create Date: 2022-11-15 14:58:22.874401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e536cc7cac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atdstate',
    sa.Column('stateid', sa.Integer(), nullable=False),
    sa.Column('statename', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('stateid')
    )
    op.create_table('tuser',
    sa.Column('tuserid', sa.Integer(), nullable=False),
    sa.Column('tusername', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.Column('adminid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adminid'], ['tuser.tuserid'], ),
    sa.PrimaryKeyConstraint('tuserid'),
    sa.UniqueConstraint('tusername')
    )
    op.create_table('group',
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.Text(), nullable=True),
    sa.Column('adminid', sa.Integer(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['adminid'], ['tuser.tuserid'], ),
    sa.PrimaryKeyConstraint('groupid')
    )
    op.create_table('lesson',
    sa.Column('lessonid', sa.Integer(), nullable=False),
    sa.Column('lessonname', sa.Text(), nullable=True),
    sa.Column('lessoncount', sa.Integer(), nullable=True),
    sa.Column('adminid', sa.Integer(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['adminid'], ['tuser.tuserid'], ),
    sa.PrimaryKeyConstraint('lessonid')
    )
    op.create_table('room',
    sa.Column('roomid', sa.Integer(), nullable=False),
    sa.Column('roomname', sa.Text(), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.Column('major', sa.Integer(), nullable=True),
    sa.Column('minor', sa.Integer(), nullable=True),
    sa.Column('adminid', sa.Integer(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['adminid'], ['tuser.tuserid'], ),
    sa.PrimaryKeyConstraint('roomid')
    )
    op.create_table('joingroups',
    sa.Column('lessonid', sa.Integer(), nullable=False),
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.ForeignKeyConstraint(['lessonid'], ['lesson.lessonid'], ),
    sa.PrimaryKeyConstraint('lessonid', 'groupid')
    )
    op.create_table('jointusers',
    sa.Column('lessonid', sa.Integer(), nullable=False),
    sa.Column('tuserid', sa.Integer(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lessonid'], ['lesson.lessonid'], ),
    sa.ForeignKeyConstraint(['tuserid'], ['tuser.tuserid'], ),
    sa.PrimaryKeyConstraint('lessonid', 'tuserid')
    )
    op.create_table('lessontask',
    sa.Column('lessontaskid', sa.Integer(), nullable=False),
    sa.Column('lessontaskdate', sa.Date(), nullable=True),
    sa.Column('periode', sa.Integer(), nullable=True),
    sa.Column('lessonid', sa.Integer(), nullable=True),
    sa.Column('roomid', sa.Integer(), nullable=True),
    sa.Column('sutime', sa.Time(), nullable=True),
    sa.Column('mistime', sa.Time(), nullable=True),
    sa.Column('notime', sa.Time(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lessonid'], ['lesson.lessonid'], ),
    sa.ForeignKeyConstraint(['roomid'], ['room.roomid'], ),
    sa.PrimaryKeyConstraint('lessontaskid')
    )
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('adminid', sa.Integer(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['adminid'], ['tuser.tuserid'], ),
    sa.ForeignKeyConstraint(['groupid'], ['group.groupid'], ),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tasklog',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('lessontaskid', sa.Integer(), nullable=False),
    sa.Column('atdtime', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('delete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lessontaskid'], ['lessontask.lessontaskid'], ),
    sa.ForeignKeyConstraint(['state'], ['atdstate.stateid'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('userid', 'lessontaskid')
    )
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('delete_flg', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blocklist_jti'), 'token_blocklist', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blocklist_jti'), table_name='token_blocklist')
    op.drop_table('token_blocklist')
    op.drop_table('tasklog')
    op.drop_table('user')
    op.drop_table('lessontask')
    op.drop_table('jointusers')
    op.drop_table('joingroups')
    op.drop_table('room')
    op.drop_table('lesson')
    op.drop_table('group')
    op.drop_table('tuser')
    op.drop_table('atdstate')
    # ### end Alembic commands ###
